version: '3.8'

services:
  pqdb: 
    container_name: postgres-db
    # jika nama file adalah Dockerfile gunakan yang dibawah ini
    # build: ./
    # jika nama file bukan Dockerfile
    build: 
      context: ./ # folder dimana dockerfile berada
      dockerfile: Dockerfile.development # nama file
    # versi short syntax
    # ports:
    #   - 8080:8080
    # versi long syntax
    ports:
      - protocol: tcp
        published: 5432
        target: 5432
    environment:
      - POSTGRES_PASSWORD=mimin