version: '3.8'

services:
  app:
    build: ./
    environment:
      - APP_PORT=8080
      - MODE=local
    deploy:
      resources:
        reservations:
          cpus: "0.15"
          memory: 15M
        limits:
          cpus: "0.30"
          memory: 30M

networks:
  core-network:
    driver: bridge
