version: '3.8'

services:

  postgres:
    container_name: pqdb
    image: postgres:11.22-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mimin
    volumes:
      - type: volume
        source: pqdb
        target: "/var/lib/postgresql/data"
        read_only: false

volumes:
  pqdb:
    name: postgres-volume